com::ethernom::android::etherapi::linkLayer::EtherBTAdapter
String com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.TAG
Referenced by com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.CardOpen.
UUID com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.ETH_serviceUUID
UUID com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.ETH_characteristicUUID
String com.ethernom.android.etherapi.linkLayer.EtherBTAdapter._adapterAddress
Referenced by com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.GetAdapterAddress, com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.SetAdapterAddress.
Context com.ethernom.android.etherapi.linkLayer.EtherBTAdapter._context
Referenced by com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.CardOpen, com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.Init.
CardInfo com.ethernom.android.etherapi.linkLayer.EtherBTAdapter._cardInfo
int com.ethernom.android.etherapi.linkLayer.EtherBTAdapter._servicePort
Referenced by com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.Init.
BluetoothAdapter com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.mBluetoothAdapter
Referenced by com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.CardOpen, com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.Init, com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.Discover.
Handler com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.mHandler
Referenced by com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.scanLeDevice, com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.Init.
long com.ethernom.android.etherapi.linkLayer.EtherBTAdapter._scanMSecsTimeout
Referenced by com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.scanLeDevice, com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.Init.
BluetoothLeScanner com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.mLEScanner
Referenced by com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.scanLeDevice, com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.CardOpen, com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.Discover.
ScanSettings com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.settings
Referenced by com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.scanLeDevice, com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.Discover.
List<ScanFilter> com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.filters
Referenced by com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.scanLeDevice, com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.Discover.
BluetoothDevice com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.periphEthCard
Referenced by com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.CardOpen.
BluetoothGatt com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.gatt
Referenced by com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.CardClose, com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.CardOpen, com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.WriteToCard.
BluetoothGattCharacteristic com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.ethCharacteristic
Referenced by com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.WriteToCard.
String com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.eth_advServiceUUD
Referenced by com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.Init, com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.Discover.
ScanCallback com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.mScanCallback
Referenced by com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.scanLeDevice, com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.CardOpen.
BluetoothGattCallback com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.gattCallback
Referenced by com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.CardOpen.
TInterface com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.GetInterface()
References com.ethernom.android.etherapi.linkLayer.TInterface.BLE.
String com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.GetAdapterAddress()
References com.ethernom.android.etherapi.linkLayer.EtherBTAdapter._adapterAddress.
void com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.SetAdapterAddress(String adapterAddress)
References com.ethernom.android.etherapi.linkLayer.EtherBTAdapter._adapterAddress.
void com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.StopDiscovery()
References com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.scanLeDevice.
void com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.CardClose()
References com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.scanLeDevice, com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.gatt, com.ethernom.android.etherapi.linkLayer.CardEventListener.onCardClosedSucess.
UUID com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.convertFromInteger(int i)
void com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.CardOpen(CardInfo cardInfo)
References com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.TAG, com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.mLEScanner, com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.mScanCallback, com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.periphEthCard, com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.mBluetoothAdapter, com.ethernom.android.etherapi.CardInfo.GetDeviceID, com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.gatt, com.ethernom.android.etherapi.linkLayer.EtherBTAdapter._context, com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.gattCallback.
void com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.Init(int servicePort, long secsTimeout, boolean allowDuplicates, boolean stopScanOnWrite, Context context)
References com.ethernom.android.etherapi.linkLayer.EtherCommAdapter._scanAllowDuplicates, com.ethernom.android.etherapi.linkLayer.EtherBTAdapter._scanMSecsTimeout, com.ethernom.android.etherapi.linkLayer.EtherCommAdapter._scanStopScanOnWrite, com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.mHandler, com.ethernom.android.etherapi.linkLayer.EtherBTAdapter._context, com.ethernom.android.etherapi.linkLayer.EtherBTAdapter._servicePort, com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.mBluetoothAdapter, com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.eth_advServiceUUD.
void com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.Discover()
References com.ethernom.android.etherapi.linkLayer.EtherCommAdapter._foundCards, com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.mLEScanner, com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.mBluetoothAdapter, com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.settings, com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.filters, com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.eth_advServiceUUD, com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.scanLeDevice.
void com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.WriteToCard(byte[] transportPacket)
References com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.ethCharacteristic, com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.gatt.
void com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.scanLeDevice(final boolean enable)
References com.ethernom.android.etherapi.linkLayer.EtherBTAdapter._scanMSecsTimeout, com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.mHandler, com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.mLEScanner, com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.mScanCallback, com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.filters, com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.settings.
Referenced by com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.StopDiscovery, com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.CardClose, com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.Discover.