com::ethernom::android::etherapi::EtherAPI
String com.ethernom.android.etherapi.EtherAPI.TAG
Referenced by com.ethernom.android.etherapi.EtherAPI.SetupCardListeners, com.ethernom.android.etherapi.EtherAPI.StopDiscovery, com.ethernom.android.etherapi.EtherAPI.DiscoverDevices.
int com.ethernom.android.etherapi.EtherAPI.instanceCount
Referenced by com.ethernom.android.etherapi.EtherAPI.EtherAPI.
EtherCommAdapter com.ethernom.android.etherapi.EtherAPI._adapter
Referenced by com.ethernom.android.etherapi.EtherAPI.SetupCardListeners, com.ethernom.android.etherapi.EtherAPI.EtherAPI, com.ethernom.android.etherapi.EtherAPI.StopDiscovery, com.ethernom.android.etherapi.EtherAPI.CardClose, com.ethernom.android.etherapi.EtherAPI.DiscoverDevices, com.ethernom.android.etherapi.EtherAPI.Select, com.ethernom.android.etherapi.EtherAPI.Write.
Context com.ethernom.android.etherapi.EtherAPI._thisContext
Referenced by com.ethernom.android.etherapi.EtherAPI.EtherAPI.
EtherTransportProtocol com.ethernom.android.etherapi.EtherAPI.transport
Referenced by com.ethernom.android.etherapi.EtherAPI.SetupCardListeners, com.ethernom.android.etherapi.EtherAPI.EtherAPI, com.ethernom.android.etherapi.EtherAPI.Write.
byte com.ethernom.android.etherapi.EtherAPI.openServiceCmd
SelectListener com.ethernom.android.etherapi.EtherAPI._selectListener
Referenced by com.ethernom.android.etherapi.EtherAPI.SetupCardListeners, com.ethernom.android.etherapi.EtherAPI.Select.
ReadListener com.ethernom.android.etherapi.EtherAPI._readListener
Referenced by com.ethernom.android.etherapi.EtherAPI.SetupCardListeners, com.ethernom.android.etherapi.EtherAPI.ClearReadListener, com.ethernom.android.etherapi.EtherAPI.SubscribeToUnsolictedEvents, com.ethernom.android.etherapi.EtherAPI.Write.
DiscoverServiceListener com.ethernom.android.etherapi.EtherAPI._discoverServiceListener
Referenced by com.ethernom.android.etherapi.EtherAPI.SetupCardListeners, com.ethernom.android.etherapi.EtherAPI.CardClose, com.ethernom.android.etherapi.EtherAPI.DiscoverDevices.
CardCloseListener com.ethernom.android.etherapi.EtherAPI._cardClosedListener
Referenced by com.ethernom.android.etherapi.EtherAPI.SetupCardListeners, com.ethernom.android.etherapi.EtherAPI.CardClose.
UnSolicitedEventListener com.ethernom.android.etherapi.EtherAPI._unSolicitedEventListener
Referenced by com.ethernom.android.etherapi.EtherAPI.SetupCardListeners, com.ethernom.android.etherapi.EtherAPI.ClearUnsolicitedEventListener, com.ethernom.android.etherapi.EtherAPI.SubscribeToUnsolictedEvents, com.ethernom.android.etherapi.EtherAPI.Write.
ConnectionEventListener com.ethernom.android.etherapi.EtherAPI._connectionEventListener
Referenced by com.ethernom.android.etherapi.EtherAPI.SetupCardListeners, com.ethernom.android.etherapi.EtherAPI.OnCardDisconnected.
long com.ethernom.android.etherapi.EtherAPI._scanSecsTimeout
boolean com.ethernom.android.etherapi.EtherAPI._scanAllowDuplicates
boolean com.ethernom.android.etherapi.EtherAPI._scanStopScanOnWrite
int com.ethernom.android.etherapi.EtherAPI.thisId
Referenced by com.ethernom.android.etherapi.EtherAPI.EtherAPI, com.ethernom.android.etherapi.EtherAPI.StopDiscovery, com.ethernom.android.etherapi.EtherAPI.DiscoverDevices, com.ethernom.android.etherapi.EtherAPIManager._InitAPI, com.ethernom.android.etherapi.EtherAPIManager._Select, com.ethernom.android.etherapi.EtherAPIManager._WriteJSON, com.ethernom.android.etherapi.EtherAPIManager._CardClose, com.ethernom.android.etherapi.EtherAPIManager._onCardDisconnected, com.ethernom.android.etherapi.EtherAPIManager._SubscribeToUnsolictedEvents, com.ethernom.android.etherapi.EtherAPIManager._StopDiscovery, com.ethernom.android.etherapi.EtherAPIManager._DiscoverDevices.
void com.ethernom.android.etherapi.EtherAPI.SetupCardListeners(EtherCommAdapter adapter)
References com.ethernom.android.etherapi.EtherAPI._adapter, com.ethernom.android.etherapi.linkLayer.EtherCommAdapter.SetDiscoverServiceEventListener, com.ethernom.android.etherapi.EtherAPI._discoverServiceListener, com.ethernom.android.etherapi.DiscoverServiceListener.onServiceDiscover, com.ethernom.android.etherapi.linkLayer.EtherCommAdapter.SetCardEventListener, com.ethernom.android.etherapi.EtherAPI._selectListener, com.ethernom.android.etherapi.SelectListener.onSelectFail, com.ethernom.android.etherapi.EtherAPI._connectionEventListener, com.ethernom.android.etherapi.ConnectionEventListener.onConnectionDropped, com.ethernom.android.etherapi.SelectListener.onSelectSuccess, com.ethernom.android.etherapi.SelectListener.onDisconnect, com.ethernom.android.etherapi.EtherAPI._cardClosedListener, com.ethernom.android.etherapi.CardCloseListener.onCardCloseSuccess, com.ethernom.android.etherapi.EtherAPI.TAG, com.ethernom.android.etherapi.EtherAPI.transport, com.ethernom.android.etherapi.EtherTransportProtocol.GetServicePort, com.ethernom.android.etherapi.EtherTransportProtocol.ETH_HEADER_SIZE, com.ethernom.android.etherapi.EtherTransportProtocol.GetTransportMessageCheckSum, com.ethernom.android.etherapi.EtherAPI._readListener, com.ethernom.android.etherapi.EtherTransportProtocol.GetApplicationData, com.ethernom.android.etherapi.ReadListener.onReadSuccess, com.ethernom.android.etherapi.EtherAPI._unSolicitedEventListener, com.ethernom.android.etherapi.UnSolicitedEventListener.onUnsolicitedEvent.
Referenced by com.ethernom.android.etherapi.EtherAPI.EtherAPI.
com.ethernom.android.etherapi.EtherAPI.EtherAPI(String adapterConnectionString, byte servicePort, long secsTimeout, boolean allowDuplicates, boolean stopScanOnWrite, Context context)
References com.ethernom.android.etherapi.EtherAPI._thisContext, com.ethernom.android.etherapi.EtherAPI.thisId, com.ethernom.android.etherapi.EtherAPI.instanceCount, com.ethernom.android.etherapi.EtherAPI._adapter, com.ethernom.android.etherapi.EtherAPI.transport, com.ethernom.android.etherapi.linkLayer.EtherCommAdapter.GetInterface, com.ethernom.android.etherapi.TMessageProtocol.APP, com.ethernom.android.etherapi.linkLayer.EtherCommAdapter.Init, com.ethernom.android.etherapi.EtherAPI.SetupCardListeners.
void com.ethernom.android.etherapi.EtherAPI.ClearUnsolicitedEventListener()
References com.ethernom.android.etherapi.EtherAPI._unSolicitedEventListener.
Referenced by com.ethernom.android.etherapi.EtherAPIManager._UnSubscribeToUnsolictedEvents.
void com.ethernom.android.etherapi.EtherAPI.ClearReadListener()
References com.ethernom.android.etherapi.EtherAPI._readListener.
Referenced by com.ethernom.android.etherapi.EtherAPIManager._WriteJSON.
void com.ethernom.android.etherapi.EtherAPI.StopDiscovery()
References com.ethernom.android.etherapi.EtherAPI.TAG, com.ethernom.android.etherapi.EtherAPI.thisId, com.ethernom.android.etherapi.EtherAPI._adapter, com.ethernom.android.etherapi.linkLayer.EtherCommAdapter.StopDiscovery.
Referenced by com.ethernom.android.etherapi.EtherAPIManager._StopDiscovery.
void com.ethernom.android.etherapi.EtherAPI.CardClose(final CardCloseListener closeListener)
References com.ethernom.android.etherapi.EtherAPI._cardClosedListener, com.ethernom.android.etherapi.EtherAPI._adapter, com.ethernom.android.etherapi.linkLayer.EtherCommAdapter.CardClose, com.ethernom.android.etherapi.EtherAPI._discoverServiceListener.
Referenced by com.ethernom.android.etherapi.EtherAPIManager._CardClose.
void com.ethernom.android.etherapi.EtherAPI.OnCardDisconnected(final ConnectionEventListener connectionEventListener)
References com.ethernom.android.etherapi.EtherAPI._connectionEventListener.
Referenced by com.ethernom.android.etherapi.EtherAPIManager._onCardDisconnected.
void com.ethernom.android.etherapi.EtherAPI.SubscribeToUnsolictedEvents(final UnSolicitedEventListener unSolicitedEventListener)
References com.ethernom.android.etherapi.EtherAPI._readListener, com.ethernom.android.etherapi.EtherAPI._unSolicitedEventListener.
Referenced by com.ethernom.android.etherapi.EtherAPIManager._SubscribeToUnsolictedEvents.
void com.ethernom.android.etherapi.EtherAPI.DiscoverDevices(final DiscoverServiceListener discoverServiceListener)
References com.ethernom.android.etherapi.EtherAPI.TAG, com.ethernom.android.etherapi.EtherAPI.thisId, com.ethernom.android.etherapi.EtherAPI._discoverServiceListener, com.ethernom.android.etherapi.EtherAPI._adapter, com.ethernom.android.etherapi.linkLayer.EtherCommAdapter.Discover.
Referenced by com.ethernom.android.etherapi.EtherAPIManager._DiscoverDevices.
void com.ethernom.android.etherapi.EtherAPI.Select(CardInfo cardInfo, final SelectListener selectListener)
References com.ethernom.android.etherapi.EtherAPI._selectListener, com.ethernom.android.etherapi.EtherAPI._adapter, com.ethernom.android.etherapi.linkLayer.EtherCommAdapter.CardOpen.
Referenced by com.ethernom.android.etherapi.EtherAPIManager._Select.
void com.ethernom.android.etherapi.EtherAPI.Write(byte [] buffer, final ReadListener readListener)
References com.ethernom.android.etherapi.EtherAPI._unSolicitedEventListener, com.ethernom.android.etherapi.EtherAPI._readListener, com.ethernom.android.etherapi.EtherAPI.transport, com.ethernom.android.etherapi.EtherTransportProtocol.GetPayload, com.ethernom.android.etherapi.EtherAPI._adapter, com.ethernom.android.etherapi.linkLayer.EtherCommAdapter.WriteToCard.
Referenced by com.ethernom.android.etherapi.EtherAPIManager._WriteJSON.
void com.ethernom.android.etherapi.EtherAPI.Write(byte cmd, final ReadListener readListener)
References com.ethernom.android.etherapi.EtherAPI._unSolicitedEventListener, com.ethernom.android.etherapi.EtherAPI._readListener, com.ethernom.android.etherapi.EtherAPI.transport, com.ethernom.android.etherapi.EtherTransportProtocol.GetPayload, com.ethernom.android.etherapi.EtherAPI._adapter, com.ethernom.android.etherapi.linkLayer.EtherCommAdapter.WriteToCard.
void com.ethernom.android.etherapi.EtherAPI.Write(byte cmd, byte [] buffer, final ReadListener readListener)
References com.ethernom.android.etherapi.EtherAPI._unSolicitedEventListener, com.ethernom.android.etherapi.EtherAPI._readListener, com.ethernom.android.etherapi.EtherAPI.transport, com.ethernom.android.etherapi.EtherTransportProtocol.GetPayload, com.ethernom.android.etherapi.EtherAPI._adapter, com.ethernom.android.etherapi.linkLayer.EtherCommAdapter.WriteToCard.
void com.ethernom.android.etherapi.EtherAPI.Write(byte cmd, String [] buffer, final ReadListener readListener)
References com.ethernom.android.etherapi.EtherAPI._unSolicitedEventListener, com.ethernom.android.etherapi.EtherAPI._readListener, com.ethernom.android.etherapi.EtherAPI.transport, com.ethernom.android.etherapi.EtherTransportProtocol.GetPayload, com.ethernom.android.etherapi.EtherAPI._adapter, com.ethernom.android.etherapi.linkLayer.EtherCommAdapter.WriteToCard.
void com.ethernom.android.etherapi.EtherAPI.Write(byte cmd, String buffer, final ReadListener readListener)
References com.ethernom.android.etherapi.EtherAPI._unSolicitedEventListener, com.ethernom.android.etherapi.EtherAPI._readListener, com.ethernom.android.etherapi.EtherAPI.transport, com.ethernom.android.etherapi.EtherTransportProtocol.GetPayload, com.ethernom.android.etherapi.EtherAPI._adapter, com.ethernom.android.etherapi.linkLayer.EtherCommAdapter.WriteToCard.
void com.ethernom.android.etherapi.EtherAPI.Write(String buffer, final ReadListener readListener)
References com.ethernom.android.etherapi.EtherAPI._unSolicitedEventListener, com.ethernom.android.etherapi.EtherAPI._readListener, com.ethernom.android.etherapi.EtherAPI.transport, com.ethernom.android.etherapi.EtherTransportProtocol.GetPayload, com.ethernom.android.etherapi.EtherAPI._adapter, com.ethernom.android.etherapi.linkLayer.EtherCommAdapter.WriteToCard.