com::ethernom::android::etherapi::EtherTransportProtocol
String com.ethernom.android.etherapi.EtherTransportProtocol.TAG
int com.ethernom.android.etherapi.EtherTransportProtocol.DELIMITER
Referenced by com.ethernom.android.etherapi.EtherAPIManager.parseToOutputJSON, com.ethernom.android.etherapi.EtherTransportProtocol.CrackTransportPacket, com.ethernom.android.etherapi.EtherTransportProtocol.GetPayload.
byte com.ethernom.android.etherapi.EtherTransportProtocol._servicePort
Referenced by com.ethernom.android.etherapi.EtherTransportProtocol.EtherTransportProtocol, com.ethernom.android.etherapi.EtherTransportProtocol.GetServicePort, com.ethernom.android.etherapi.EtherTransportProtocol.getTransportHeader.
TMessageProtocol com.ethernom.android.etherapi.EtherTransportProtocol._messageProtocol
Referenced by com.ethernom.android.etherapi.EtherTransportProtocol.EtherTransportProtocol, com.ethernom.android.etherapi.EtherTransportProtocol.getTransportHeader.
CardInfo com.ethernom.android.etherapi.EtherTransportProtocol._cardInfo
TInterface com.ethernom.android.etherapi.EtherTransportProtocol._interfaceKind
Referenced by com.ethernom.android.etherapi.EtherTransportProtocol.EtherTransportProtocol, com.ethernom.android.etherapi.EtherTransportProtocol.getTransportHeader.
byte com.ethernom.android.etherapi.EtherTransportProtocol.control
Referenced by com.ethernom.android.etherapi.EtherTransportProtocol.getTransportHeader.
int com.ethernom.android.etherapi.EtherTransportProtocol.ETH_HEADER_SIZE
Referenced by com.ethernom.android.etherapi.EtherAPI.SetupCardListeners, com.ethernom.android.etherapi.EtherTransportProtocol.GetApplicationData, com.ethernom.android.etherapi.EtherTransportProtocol.getTransportHeader.
int com.ethernom.android.etherapi.EtherTransportProtocol.ETH_PAYLOAD_HEAD
Referenced by com.ethernom.android.etherapi.EtherTransportProtocol.CrackTransportPacket.
com.ethernom.android.etherapi.EtherTransportProtocol.EtherTransportProtocol(byte servicePort, TInterface interfaceKind, TMessageProtocol messageProtocol)
References com.ethernom.android.etherapi.EtherTransportProtocol._servicePort, com.ethernom.android.etherapi.EtherTransportProtocol._messageProtocol, com.ethernom.android.etherapi.EtherTransportProtocol._interfaceKind.
byte com.ethernom.android.etherapi.EtherTransportProtocol.GetServicePort()
References com.ethernom.android.etherapi.EtherTransportProtocol._servicePort.
Referenced by com.ethernom.android.etherapi.EtherAPI.SetupCardListeners.
byte [] com.ethernom.android.etherapi.EtherTransportProtocol.GetApplicationData(byte [] data)
References com.ethernom.android.etherapi.EtherTransportProtocol.ETH_HEADER_SIZE.
Referenced by com.ethernom.android.etherapi.EtherAPI.SetupCardListeners.
byte com.ethernom.android.etherapi.EtherTransportProtocol.GetTransportMessageCheckSum(byte [] packet)
Referenced by com.ethernom.android.etherapi.EtherAPI.SetupCardListeners, com.ethernom.android.etherapi.EtherTransportProtocol.getTransportHeader.
byte [] com.ethernom.android.etherapi.EtherTransportProtocol.getTransportHeader(int payloadLength)
References com.ethernom.android.etherapi.EtherTransportProtocol.ETH_HEADER_SIZE, com.ethernom.android.etherapi.EtherTransportProtocol._servicePort, com.ethernom.android.etherapi.EtherTransportProtocol.control, com.ethernom.android.etherapi.EtherTransportProtocol._interfaceKind, com.ethernom.android.etherapi.EtherTransportProtocol._messageProtocol, com.ethernom.android.etherapi.EtherTransportProtocol.GetTransportMessageCheckSum.
Referenced by com.ethernom.android.etherapi.EtherTransportProtocol.makeTransportPacket.
byte [] com.ethernom.android.etherapi.EtherTransportProtocol.GetPayload(int cmd)
References com.ethernom.android.etherapi.EtherTransportProtocol.makeTransportPacket.
Referenced by com.ethernom.android.etherapi.EtherAPI.Write, com.ethernom.android.etherapi.EtherTransportProtocol.GetPayload.
byte [] com.ethernom.android.etherapi.EtherTransportProtocol.GetPayload(byte cmd, byte [] data)
References com.ethernom.android.etherapi.EtherTransportProtocol.makeTransportPacket.
byte [] com.ethernom.android.etherapi.EtherTransportProtocol.GetPayload(String data)
References com.ethernom.android.etherapi.EtherTransportProtocol.GetPayload.
byte [] com.ethernom.android.etherapi.EtherTransportProtocol.GetPayload(byte cmd, String data)
References com.ethernom.android.etherapi.EtherTransportProtocol.GetPayload.
byte [] com.ethernom.android.etherapi.EtherTransportProtocol.GetPayload(byte [] data)
References com.ethernom.android.etherapi.EtherTransportProtocol.makeTransportPacket.
byte [] com.ethernom.android.etherapi.EtherTransportProtocol.GetPayload(int cmd, String [] data)
References com.ethernom.android.etherapi.EtherTransportProtocol.DELIMITER, com.ethernom.android.etherapi.EtherTransportProtocol.makeTransportPacket.
String com.ethernom.android.etherapi.EtherTransportProtocol.getStringRepresentation(ArrayList< Character > list)
Referenced by com.ethernom.android.etherapi.EtherTransportProtocol.CrackTransportPacket.
ArrayList<String> com.ethernom.android.etherapi.EtherTransportProtocol.CrackTransportPacket(byte [] data)
References com.ethernom.android.etherapi.EtherTransportProtocol.ETH_PAYLOAD_HEAD, com.ethernom.android.etherapi.EtherTransportProtocol.DELIMITER, com.ethernom.android.etherapi.EtherTransportProtocol.getStringRepresentation.
byte [] com.ethernom.android.etherapi.EtherTransportProtocol.makeTransportPacket(List< Byte > payload)
References com.ethernom.android.etherapi.EtherTransportProtocol.getTransportHeader.
Referenced by com.ethernom.android.etherapi.EtherTransportProtocol.GetPayload.