com::ethernom::android::etherapi::EtherAPIManager
final String com.ethernom.android.etherapi.EtherAPIManager.TAG
Referenced by com.ethernom.android.etherapi.EtherAPIManager.EtherAPIManager, com.ethernom.android.etherapi.EtherAPIManager.onActivityResult, com.ethernom.android.etherapi.EtherAPIManager._InitAPI, com.ethernom.android.etherapi.EtherAPIManager._Select, com.ethernom.android.etherapi.EtherAPIManager.GetEthernomTypeValue, com.ethernom.android.etherapi.EtherAPIManager.AddToPayload, com.ethernom.android.etherapi.EtherAPIManager.parseToOutputJSON, com.ethernom.android.etherapi.EtherAPIManager._WriteJSON, com.ethernom.android.etherapi.EtherAPIManager._CardClose, com.ethernom.android.etherapi.EtherAPIManager._onCardDisconnected, com.ethernom.android.etherapi.EtherAPIManager._SubscribeToUnsolictedEvents, com.ethernom.android.etherapi.EtherAPIManager._UnSubscribeToUnsolictedEvents, com.ethernom.android.etherapi.EtherAPIManager._StopDiscovery, com.ethernom.android.etherapi.EtherAPIManager._DiscoverDevices.
HashMap<Integer,EtherAPI> com.ethernom.android.etherapi.EtherAPIManager.etherApiInstances
Referenced by com.ethernom.android.etherapi.EtherAPIManager._InitAPI, com.ethernom.android.etherapi.EtherAPIManager._Select, com.ethernom.android.etherapi.EtherAPIManager._WriteJSON, com.ethernom.android.etherapi.EtherAPIManager._CardClose, com.ethernom.android.etherapi.EtherAPIManager._onCardDisconnected, com.ethernom.android.etherapi.EtherAPIManager._SubscribeToUnsolictedEvents, com.ethernom.android.etherapi.EtherAPIManager._UnSubscribeToUnsolictedEvents, com.ethernom.android.etherapi.EtherAPIManager._StopDiscovery, com.ethernom.android.etherapi.EtherAPIManager._DiscoverDevices.
Context com.ethernom.android.etherapi.EtherAPIManager._context
Referenced by com.ethernom.android.etherapi.EtherAPIManager.EtherAPIManager, com.ethernom.android.etherapi.EtherAPIManager._InitAPI.
ReactApplicationContext com.ethernom.android.etherapi.EtherAPIManager.reactContext
Referenced by com.ethernom.android.etherapi.EtherAPIManager.getReactContext, com.ethernom.android.etherapi.EtherAPIManager.EtherAPIManager, com.ethernom.android.etherapi.EtherAPIManager._onCardDisconnected, com.ethernom.android.etherapi.EtherAPIManager._SubscribeToUnsolictedEvents, com.ethernom.android.etherapi.EtherAPIManager._DiscoverDevices.
Integer com.ethernom.android.etherapi.EtherAPIManager.instanceCount
Referenced by com.ethernom.android.etherapi.EtherAPIManager._InitAPI.
int com.ethernom.android.etherapi.EtherAPIManager.ETH_STRING_AS_UNICODE
Referenced by com.ethernom.android.etherapi.EtherAPIManager.GetEthernomTypeValue.
int com.ethernom.android.etherapi.EtherAPIManager.ETH_STRING_AS_ASUTF8
Referenced by com.ethernom.android.etherapi.EtherAPIManager.GetEthernomTypeValue.
int com.ethernom.android.etherapi.EtherAPIManager.ETH_INT_AS_BYTE
Referenced by com.ethernom.android.etherapi.EtherAPIManager.GetEthernomTypeValue.
int com.ethernom.android.etherapi.EtherAPIManager.ETH_INT_AS_2BYTE
Referenced by com.ethernom.android.etherapi.EtherAPIManager.GetEthernomTypeValue.
int com.ethernom.android.etherapi.EtherAPIManager.ETH_UNICODESTRING
int com.ethernom.android.etherapi.EtherAPIManager.ETH_UTF8STRING
Referenced by com.ethernom.android.etherapi.EtherAPIManager.parseToOutputJSON.
int com.ethernom.android.etherapi.EtherAPIManager.ETH_BYTE
Referenced by com.ethernom.android.etherapi.EtherAPIManager.parseToOutputJSON.
int com.ethernom.android.etherapi.EtherAPIManager.ETH_2BYTE
Referenced by com.ethernom.android.etherapi.EtherAPIManager.parseToOutputJSON.
int com.ethernom.android.etherapi.EtherAPIManager.ETH_PAYLOAD
Referenced by com.ethernom.android.etherapi.EtherAPIManager.parseToOutputJSON.
ReactApplicationContext com.ethernom.android.etherapi.EtherAPIManager.getReactContext()
References com.ethernom.android.etherapi.EtherAPIManager.reactContext.
com.ethernom.android.etherapi.EtherAPIManager.EtherAPIManager(ReactApplicationContext reactContext)
References com.ethernom.android.etherapi.EtherAPIManager.reactContext, com.ethernom.android.etherapi.EtherAPIManager._context, com.ethernom.android.etherapi.EtherAPIManager.TAG.
String com.ethernom.android.etherapi.EtherAPIManager.getName()
void com.ethernom.android.etherapi.EtherAPIManager.onActivityResult(int requestCode, int resultCode, Intent data)
References com.ethernom.android.etherapi.EtherAPIManager.TAG.
void com.ethernom.android.etherapi.EtherAPIManager._InitAPI(final String adapterConnectionString, int servicePort, int secsTimeout, boolean allowDuplicates, boolean stopScanOnWrite, final Callback callback)
References com.ethernom.android.etherapi.EtherAPIManager.TAG, com.ethernom.android.etherapi.EtherAPIManager._context, com.ethernom.android.etherapi.EtherAPIManager.etherApiInstances, com.ethernom.android.etherapi.EtherAPIManager.instanceCount, com.ethernom.android.etherapi.EtherAPI.thisId.
void com.ethernom.android.etherapi.EtherAPIManager._Select(Integer instanceHandle, String deviceID, String deviceName, final Callback callback)
References com.ethernom.android.etherapi.EtherAPIManager.TAG, com.ethernom.android.etherapi.EtherAPIManager.etherApiInstances, com.ethernom.android.etherapi.EtherAPI.thisId, com.ethernom.android.etherapi.EtherAPI.Select.
void com.ethernom.android.etherapi.EtherAPIManager._WriteJSON(Integer instanceHandle, String json, final String outPutJSONDef, final Callback callback)
References com.ethernom.android.etherapi.EtherAPIManager.etherApiInstances, com.ethernom.android.etherapi.EtherAPIManager.TAG, com.ethernom.android.etherapi.EtherAPI.thisId, com.ethernom.android.etherapi.EtherAPIManager.AddToPayload, com.ethernom.android.etherapi.Utils.BytetobyteArray, com.ethernom.android.etherapi.EtherAPI.Write, com.ethernom.android.etherapi.EtherAPI.ClearReadListener, com.ethernom.android.etherapi.EtherAPIManager.parseToOutputJSON.
void com.ethernom.android.etherapi.EtherAPIManager._CardClose(Integer instanceHandle, final Callback callback)
References com.ethernom.android.etherapi.EtherAPIManager.etherApiInstances, com.ethernom.android.etherapi.EtherAPIManager.TAG, com.ethernom.android.etherapi.EtherAPI.thisId, com.ethernom.android.etherapi.EtherAPI.CardClose.
void com.ethernom.android.etherapi.EtherAPIManager._onCardDisconnected(Integer instanceHandle, final String callbackEventName)
References com.ethernom.android.etherapi.EtherAPIManager.etherApiInstances, com.ethernom.android.etherapi.EtherAPIManager.TAG, com.ethernom.android.etherapi.EtherAPI.thisId, com.ethernom.android.etherapi.EtherAPI.OnCardDisconnected, com.ethernom.android.etherapi.EtherAPIManager.reactContext.
void com.ethernom.android.etherapi.EtherAPIManager._SubscribeToUnsolictedEvents(Integer instanceHandle, final String outPutJSONDef, final String callbackEventName)
References com.ethernom.android.etherapi.EtherAPIManager.etherApiInstances, com.ethernom.android.etherapi.EtherAPIManager.TAG, com.ethernom.android.etherapi.EtherAPI.thisId, com.ethernom.android.etherapi.EtherAPI.SubscribeToUnsolictedEvents, com.ethernom.android.etherapi.EtherAPIManager.parseToOutputJSON, com.ethernom.android.etherapi.EtherAPIManager.reactContext.
void com.ethernom.android.etherapi.EtherAPIManager._UnSubscribeToUnsolictedEvents(Integer instanceHandle, final String callbackEventName)
References com.ethernom.android.etherapi.EtherAPIManager.etherApiInstances, com.ethernom.android.etherapi.EtherAPIManager.TAG, com.ethernom.android.etherapi.EtherAPI.ClearUnsolicitedEventListener.
void com.ethernom.android.etherapi.EtherAPIManager._StopDiscovery(Integer instanceHandle)
References com.ethernom.android.etherapi.EtherAPIManager.etherApiInstances, com.ethernom.android.etherapi.EtherAPIManager.TAG, com.ethernom.android.etherapi.EtherAPI.thisId, com.ethernom.android.etherapi.EtherAPI.StopDiscovery.
void com.ethernom.android.etherapi.EtherAPIManager._DiscoverDevices(Integer instanceHandle, final String callbackEventName)
References com.ethernom.android.etherapi.EtherAPIManager.etherApiInstances, com.ethernom.android.etherapi.EtherAPIManager.TAG, com.ethernom.android.etherapi.EtherAPI.thisId, com.ethernom.android.etherapi.EtherAPI.DiscoverDevices, com.ethernom.android.etherapi.EtherAPIManager.reactContext.
List<Byte> com.ethernom.android.etherapi.EtherAPIManager.GetEthernomTypeValue(JSONObject jObj, int encoding)
References com.ethernom.android.etherapi.EtherAPIManager.ETH_STRING_AS_UNICODE, com.ethernom.android.etherapi.Utils.GetDelimitedString, com.ethernom.android.etherapi.EtherAPIManager.ETH_STRING_AS_ASUTF8, com.ethernom.android.etherapi.EtherAPIManager.ETH_INT_AS_BYTE, com.ethernom.android.etherapi.EtherAPIManager.ETH_INT_AS_2BYTE, com.ethernom.android.etherapi.EtherAPIManager.TAG.
Referenced by com.ethernom.android.etherapi.EtherAPIManager.AddToPayload.
List<Byte> com.ethernom.android.etherapi.EtherAPIManager.AddToPayload(JSONObject jObj, List< Byte >currentPayload)
References com.ethernom.android.etherapi.EtherAPIManager.TAG, com.ethernom.android.etherapi.Utils.GetDelimitedString, com.ethernom.android.etherapi.Utils.GetEndedString, com.ethernom.android.etherapi.EtherAPIManager.GetEthernomTypeValue.
Referenced by com.ethernom.android.etherapi.EtherAPIManager._WriteJSON.
String com.ethernom.android.etherapi.EtherAPIManager.parseToOutputJSON(byte[] payload, String outputJSONDef)
References com.ethernom.android.etherapi.EtherAPIManager.ETH_BYTE, com.ethernom.android.etherapi.EtherAPIManager.ETH_2BYTE, com.ethernom.android.etherapi.EtherAPIManager.ETH_UTF8STRING, com.ethernom.android.etherapi.EtherTransportProtocol.DELIMITER, com.ethernom.android.etherapi.Utils.ByteListtobyteArray, com.ethernom.android.etherapi.EtherAPIManager.ETH_PAYLOAD, com.ethernom.android.etherapi.EtherAPIManager.TAG.
Referenced by com.ethernom.android.etherapi.EtherAPIManager._WriteJSON, com.ethernom.android.etherapi.EtherAPIManager._SubscribeToUnsolictedEvents.