com::ethernom::android::etherapi::linkLayer::EtherCommAdapter
int com.ethernom.android.etherapi.linkLayer.EtherCommAdapter.SCAN_FOREVER
boolean com.ethernom.android.etherapi.linkLayer.EtherCommAdapter._scanAllowDuplicates
Referenced by com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.Init.
long com.ethernom.android.etherapi.linkLayer.EtherCommAdapter._scanSecsTimeout
ArrayList<CardInfo> com.ethernom.android.etherapi.linkLayer.EtherCommAdapter._foundCards
Referenced by com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.Discover.
boolean com.ethernom.android.etherapi.linkLayer.EtherCommAdapter._scanStopScanOnWrite
Referenced by com.ethernom.android.etherapi.linkLayer.EtherBTAdapter.Init.
CardEventListener com.ethernom.android.etherapi.linkLayer.EtherCommAdapter.CardEventListener
DiscoverServiceListener com.ethernom.android.etherapi.linkLayer.EtherCommAdapter.DiscoverServiceEventListener
Referenced by com.ethernom.android.etherapi.linkLayer.EtherCommAdapter.SetDiscoverServiceEventListener.
abstract TInterface com.ethernom.android.etherapi.linkLayer.EtherCommAdapter.GetInterface()
Referenced by com.ethernom.android.etherapi.EtherAPI.EtherAPI.
abstract void com.ethernom.android.etherapi.linkLayer.EtherCommAdapter.Init(int servicePort, long secsTimeout, boolean allowDuplicates, boolean stopScanOnWrite, Context context)
Referenced by com.ethernom.android.etherapi.EtherAPI.EtherAPI.
abstract String com.ethernom.android.etherapi.linkLayer.EtherCommAdapter.GetAdapterAddress()
abstract void com.ethernom.android.etherapi.linkLayer.EtherCommAdapter.SetAdapterAddress(String address)
abstract void com.ethernom.android.etherapi.linkLayer.EtherCommAdapter.Discover()
Referenced by com.ethernom.android.etherapi.EtherAPI.DiscoverDevices.
abstract void com.ethernom.android.etherapi.linkLayer.EtherCommAdapter.StopDiscovery()
Referenced by com.ethernom.android.etherapi.EtherAPI.StopDiscovery.
abstract void com.ethernom.android.etherapi.linkLayer.EtherCommAdapter.CardOpen(CardInfo cardInfo)
Referenced by com.ethernom.android.etherapi.EtherAPI.Select.
abstract void com.ethernom.android.etherapi.linkLayer.EtherCommAdapter.CardClose()
Referenced by com.ethernom.android.etherapi.EtherAPI.CardClose.
void com.ethernom.android.etherapi.linkLayer.EtherCommAdapter.SetCardEventListener(CardEventListener listener)
Referenced by com.ethernom.android.etherapi.EtherAPI.SetupCardListeners.
void com.ethernom.android.etherapi.linkLayer.EtherCommAdapter.SetDiscoverServiceEventListener(DiscoverServiceListener listener)
References com.ethernom.android.etherapi.linkLayer.EtherCommAdapter.DiscoverServiceEventListener.
Referenced by com.ethernom.android.etherapi.EtherAPI.SetupCardListeners.
abstract void com.ethernom.android.etherapi.linkLayer.EtherCommAdapter.WriteToCard(byte [] buffer)
Referenced by com.ethernom.android.etherapi.EtherAPI.Write.