com::ethernom::android::etherapi::Utils
static byte [] com.ethernom.android.etherapi.Utils.BytetobyteArray(Byte [] bytes)
Referenced by com.ethernom.android.etherapi.EtherAPIManager._WriteJSON.
static byte [] com.ethernom.android.etherapi.Utils.ByteListtobyteArray(List< Byte > in)
Referenced by com.ethernom.android.etherapi.EtherAPIManager.parseToOutputJSON.
static List<Byte> com.ethernom.android.etherapi.Utils.GetDelimitedString(String data)
Referenced by com.ethernom.android.etherapi.EtherAPIManager.GetEthernomTypeValue, com.ethernom.android.etherapi.EtherAPIManager.AddToPayload.
static List<Byte> com.ethernom.android.etherapi.Utils.GetEndedString(String data)
Referenced by com.ethernom.android.etherapi.EtherAPIManager.AddToPayload.