.TH "com.ethernom.android.etherapi.CardInfo" 3 "Fri Nov 1 2019" "EtherAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.ethernom.android.etherapi.CardInfo
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "String \fBGetCardName\fP ()"
.br
.ti -1c
.RI "String \fBGetDeviceID\fP ()"
.br
.ti -1c
.RI "\fBCardInfo\fP (String name, String manufacturingID)"
.br
.in -1c
.SS "Package Attributes"

.in +1c
.ti -1c
.RI "String \fB_cardName\fP"
.br
.ti -1c
.RI "String \fB_deviceID\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file CardInfo\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "com\&.ethernom\&.android\&.etherapi\&.CardInfo\&.CardInfo (String name, String manufacturingID)"

.PP
Definition at line 12 of file CardInfo\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "String com\&.ethernom\&.android\&.etherapi\&.CardInfo\&.GetCardName ()"

.PP
Definition at line 8 of file CardInfo\&.java\&.
.SS "String com\&.ethernom\&.android\&.etherapi\&.CardInfo\&.GetDeviceID ()"

.PP
Definition at line 10 of file CardInfo\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "String com\&.ethernom\&.android\&.etherapi\&.CardInfo\&._cardName\fC [package]\fP"

.PP
Definition at line 5 of file CardInfo\&.java\&.
.SS "String com\&.ethernom\&.android\&.etherapi\&.CardInfo\&._deviceID\fC [package]\fP"

.PP
Definition at line 6 of file CardInfo\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for EtherAPI from the source code\&.
