.TH "com.ethernom.android.etherapi.linkLayer" 3 "Fri Nov 1 2019" "EtherAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.ethernom.android.etherapi.linkLayer
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCardEventListener\fP"
.br
.ti -1c
.RI "class \fBEtherBTAdapter\fP"
.br
.ti -1c
.RI "class \fBEtherCommAdapter\fP"
.br
.ti -1c
.RI "enum \fBTInterface\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for EtherAPI from the source code\&.
