.TH "com.ethernom.android.etherapi.BuildConfig" 3 "Fri Nov 1 2019" "EtherAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.ethernom.android.etherapi.BuildConfig
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static final boolean \fBDEBUG\fP = Boolean\&.parseBoolean('true')"
.br
.ti -1c
.RI "static final String \fBAPPLICATION_ID\fP = 'com\&.ethernom\&.android\&.etherapi'"
.br
.ti -1c
.RI "static final String \fBBUILD_TYPE\fP = 'debug'"
.br
.ti -1c
.RI "static final String \fBFLAVOR\fP = ''"
.br
.ti -1c
.RI "static final int \fBVERSION_CODE\fP = \-1"
.br
.ti -1c
.RI "static final String \fBVERSION_NAME\fP = ''"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 6 of file BuildConfig\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "final String com\&.ethernom\&.android\&.etherapi\&.BuildConfig\&.APPLICATION_ID = 'com\&.ethernom\&.android\&.etherapi'\fC [static]\fP"

.PP
Definition at line 8 of file BuildConfig\&.java\&.
.SS "final String com\&.ethernom\&.android\&.etherapi\&.BuildConfig\&.BUILD_TYPE = 'debug'\fC [static]\fP"

.PP
Definition at line 9 of file BuildConfig\&.java\&.
.SS "final boolean com\&.ethernom\&.android\&.etherapi\&.BuildConfig\&.DEBUG = Boolean\&.parseBoolean('true')\fC [static]\fP"

.PP
Definition at line 7 of file BuildConfig\&.java\&.
.SS "final String com\&.ethernom\&.android\&.etherapi\&.BuildConfig\&.FLAVOR = ''\fC [static]\fP"

.PP
Definition at line 10 of file BuildConfig\&.java\&.
.SS "final int com\&.ethernom\&.android\&.etherapi\&.BuildConfig\&.VERSION_CODE = \-1\fC [static]\fP"

.PP
Definition at line 11 of file BuildConfig\&.java\&.
.SS "final String com\&.ethernom\&.android\&.etherapi\&.BuildConfig\&.VERSION_NAME = ''\fC [static]\fP"

.PP
Definition at line 12 of file BuildConfig\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for EtherAPI from the source code\&.
