.TH "com.ethernom.android.etherapi.EtherError" 3 "Fri Nov 1 2019" "EtherAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.ethernom.android.etherapi.EtherError
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static int \fBETH_SUCCESS\fP = 0"
.br
.ti -1c
.RI "static int \fBETH_FAIL\fP = \-1"
.br
.ti -1c
.RI "static int \fBETH_DISCOVERY_COMPLETE\fP = 0X1001"
.br
.ti -1c
.RI "static int \fBETH_SCAN_FOREVER\fP = 0X1002"
.br
.ti -1c
.RI "static int \fBERR_ETH_CARDSCAN_FAILED\fP = 0x0101"
.br
.ti -1c
.RI "static int \fBERR_ETH_SELECT_DENIED\fP = 0x0102"
.br
.ti -1c
.RI "static int \fBERR_ETH_SELECT_FAILED\fP = 0x0103"
.br
.ti -1c
.RI "static int \fBERR_ETH_DISCONNECTED\fP = 0x0104"
.br
.ti -1c
.RI "static int \fBERR_ETH_SERVICE_OPEN_DENIED\fP = 0x0201"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file EtherError\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "int com\&.ethernom\&.android\&.etherapi\&.EtherError\&.ERR_ETH_CARDSCAN_FAILED = 0x0101\fC [static]\fP"

.PP
Definition at line 11 of file EtherError\&.java\&.
.SS "int com\&.ethernom\&.android\&.etherapi\&.EtherError\&.ERR_ETH_DISCONNECTED = 0x0104\fC [static]\fP"

.PP
Definition at line 16 of file EtherError\&.java\&.
.SS "int com\&.ethernom\&.android\&.etherapi\&.EtherError\&.ERR_ETH_SELECT_DENIED = 0x0102\fC [static]\fP"

.PP
Definition at line 14 of file EtherError\&.java\&.
.SS "int com\&.ethernom\&.android\&.etherapi\&.EtherError\&.ERR_ETH_SELECT_FAILED = 0x0103\fC [static]\fP"

.PP
Definition at line 15 of file EtherError\&.java\&.
.SS "int com\&.ethernom\&.android\&.etherapi\&.EtherError\&.ERR_ETH_SERVICE_OPEN_DENIED = 0x0201\fC [static]\fP"

.PP
Definition at line 19 of file EtherError\&.java\&.
.SS "int com\&.ethernom\&.android\&.etherapi\&.EtherError\&.ETH_DISCOVERY_COMPLETE = 0X1001\fC [static]\fP"

.PP
Definition at line 7 of file EtherError\&.java\&.
.SS "int com\&.ethernom\&.android\&.etherapi\&.EtherError\&.ETH_FAIL = \-1\fC [static]\fP"

.PP
Definition at line 5 of file EtherError\&.java\&.
.SS "int com\&.ethernom\&.android\&.etherapi\&.EtherError\&.ETH_SCAN_FOREVER = 0X1002\fC [static]\fP"

.PP
Definition at line 8 of file EtherError\&.java\&.
.SS "int com\&.ethernom\&.android\&.etherapi\&.EtherError\&.ETH_SUCCESS = 0\fC [static]\fP"

.PP
Definition at line 4 of file EtherError\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for EtherAPI from the source code\&.
