.TH "com.ethernom.android.etherapi.ServiceEventListener" 3 "Fri Nov 1 2019" "EtherAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.ethernom.android.etherapi.ServiceEventListener
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "abstract void \fBonWriteSuccess\fP (int resultCode)"
.br
.ti -1c
.RI "abstract void \fBonWriteFail\fP (int resultCode, int hwSpecificError)"
.br
.ti -1c
.RI "abstract void \fBonServiceClosedSucess\fP (int resultCode)"
.br
.ti -1c
.RI "abstract void \fBonServiceClosedFail\fP (int resultCode, int hwSpecificError)"
.br
.ti -1c
.RI "abstract void \fBonServiceClosedByService\fP (int resultCode)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file ServiceEventListener\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "abstract void com\&.ethernom\&.android\&.etherapi\&.ServiceEventListener\&.onServiceClosedByService (int resultCode)\fC [abstract]\fP"

.SS "abstract void com\&.ethernom\&.android\&.etherapi\&.ServiceEventListener\&.onServiceClosedFail (int resultCode, int hwSpecificError)\fC [abstract]\fP"

.SS "abstract void com\&.ethernom\&.android\&.etherapi\&.ServiceEventListener\&.onServiceClosedSucess (int resultCode)\fC [abstract]\fP"

.SS "abstract void com\&.ethernom\&.android\&.etherapi\&.ServiceEventListener\&.onWriteFail (int resultCode, int hwSpecificError)\fC [abstract]\fP"

.SS "abstract void com\&.ethernom\&.android\&.etherapi\&.ServiceEventListener\&.onWriteSuccess (int resultCode)\fC [abstract]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for EtherAPI from the source code\&.
