.TH "com.ethernom.android.etherapi.SelectListener" 3 "Fri Nov 1 2019" "EtherAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.ethernom.android.etherapi.SelectListener
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBonSelectSuccess\fP (int resultCode)"
.br
.ti -1c
.RI "void \fBonSelectFail\fP (int resultCode, int hwSpecificError)"
.br
.ti -1c
.RI "void \fBonDisconnect\fP (int resultCode, int hwSpecificError)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file SelectListener\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void com\&.ethernom\&.android\&.etherapi\&.SelectListener\&.onDisconnect (int resultCode, int hwSpecificError)"

.SS "void com\&.ethernom\&.android\&.etherapi\&.SelectListener\&.onSelectFail (int resultCode, int hwSpecificError)"

.SS "void com\&.ethernom\&.android\&.etherapi\&.SelectListener\&.onSelectSuccess (int resultCode)"


.SH "Author"
.PP 
Generated automatically by Doxygen for EtherAPI from the source code\&.
