.TH "com.ethernom.android.etherapi.Utils" 3 "Fri Nov 1 2019" "EtherAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.ethernom.android.etherapi.Utils
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static byte [] \fBBytetobyteArray\fP (Byte [] bytes)"
.br
.ti -1c
.RI "static byte [] \fBByteListtobyteArray\fP (List< Byte > in)"
.br
.ti -1c
.RI "static List< Byte > \fBGetDelimitedString\fP (String data)"
.br
.ti -1c
.RI "static List< Byte > \fBGetEndedString\fP (String data)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 9 of file Utils\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "static byte [] com\&.ethernom\&.android\&.etherapi\&.Utils\&.ByteListtobyteArray (List< Byte > in)\fC [static]\fP"

.PP
Definition at line 18 of file Utils\&.java\&.
.SS "static byte [] com\&.ethernom\&.android\&.etherapi\&.Utils\&.BytetobyteArray (Byte [] bytes)\fC [static]\fP"

.PP
Definition at line 10 of file Utils\&.java\&.
.SS "static List<Byte> com\&.ethernom\&.android\&.etherapi\&.Utils\&.GetDelimitedString (String data)\fC [static]\fP"

.PP
Definition at line 27 of file Utils\&.java\&.
.SS "static List<Byte> com\&.ethernom\&.android\&.etherapi\&.Utils\&.GetEndedString (String data)\fC [static]\fP"

.PP
Definition at line 49 of file Utils\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for EtherAPI from the source code\&.
