.TH "com.ethernom.android.etherapi.ReadListener" 3 "Fri Nov 1 2019" "EtherAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.ethernom.android.etherapi.ReadListener
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBonReadSuccess\fP (int resultCode, byte[] payload)"
.br
.ti -1c
.RI "void \fBonReadFail\fP (int resultCode, int hwSpecificError)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file ReadListener\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void com\&.ethernom\&.android\&.etherapi\&.ReadListener\&.onReadFail (int resultCode, int hwSpecificError)"

.SS "void com\&.ethernom\&.android\&.etherapi\&.ReadListener\&.onReadSuccess (int resultCode, byte [] payload)"


.SH "Author"
.PP 
Generated automatically by Doxygen for EtherAPI from the source code\&.
