.TH "com.ethernom.android.etherapi.EtherNFCAdapter" 3 "Fri Nov 1 2019" "EtherAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.ethernom.android.etherapi.EtherNFCAdapter
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Definition at line 3 of file EtherNFCAdapter\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for EtherAPI from the source code\&.
