.TH "com.ethernom.android.etherapi.CardCloseListener" 3 "Fri Nov 1 2019" "EtherAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.ethernom.android.etherapi.CardCloseListener
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBonCardCloseSuccess\fP (int resultCode)"
.br
.ti -1c
.RI "void \fBonCardCloseFail\fP (int resultCode, int hwSpecificError)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file CardCloseListener\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void com\&.ethernom\&.android\&.etherapi\&.CardCloseListener\&.onCardCloseFail (int resultCode, int hwSpecificError)"

.SS "void com\&.ethernom\&.android\&.etherapi\&.CardCloseListener\&.onCardCloseSuccess (int resultCode)"


.SH "Author"
.PP 
Generated automatically by Doxygen for EtherAPI from the source code\&.
