.TH "com.ethernom.android.etherapi.DiscoverServiceListener" 3 "Fri Nov 1 2019" "EtherAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.ethernom.android.etherapi.DiscoverServiceListener
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBonServiceDiscover\fP (int resultCode, String deviceID, String deviceName)"
.br
.ti -1c
.RI "void \fBonServiceDiscoverFail\fP (int resultCode, int hwSpecificError)"
.br
.ti -1c
.RI "void \fBonServiceDiscoverEnd\fP (int resultCode)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file DiscoverServiceListener\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void com\&.ethernom\&.android\&.etherapi\&.DiscoverServiceListener\&.onServiceDiscover (int resultCode, String deviceID, String deviceName)"

.SS "void com\&.ethernom\&.android\&.etherapi\&.DiscoverServiceListener\&.onServiceDiscoverEnd (int resultCode)"

.SS "void com\&.ethernom\&.android\&.etherapi\&.DiscoverServiceListener\&.onServiceDiscoverFail (int resultCode, int hwSpecificError)"


.SH "Author"
.PP 
Generated automatically by Doxygen for EtherAPI from the source code\&.
