.TH "com.ethernom.android.etherapi.TMessageProtocol" 3 "Fri Nov 1 2019" "EtherAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.ethernom.android.etherapi.TMessageProtocol
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBAPP\fP =(0x0)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBTMessageProtocol\fP (int \fBtMessageProtocolCode\fP)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "final int \fBtMessageProtocolCode\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file TMessageProtocol\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "com\&.ethernom\&.android\&.etherapi\&.TMessageProtocol\&.TMessageProtocol (int tMessageProtocolCode)\fC [private]\fP"

.PP
Definition at line 8 of file TMessageProtocol\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "com\&.ethernom\&.android\&.etherapi\&.TMessageProtocol\&.APP =(0x0)"

.PP
Definition at line 4 of file TMessageProtocol\&.java\&.
.SS "final int com\&.ethernom\&.android\&.etherapi\&.TMessageProtocol\&.tMessageProtocolCode\fC [private]\fP"

.PP
Definition at line 6 of file TMessageProtocol\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for EtherAPI from the source code\&.
