.TH "com.ethernom.android.etherapi.linkLayer.TInterface" 3 "Fri Nov 1 2019" "EtherAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.ethernom.android.etherapi.linkLayer.TInterface
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBUSB\fP =(0x1)"
.br
.ti -1c
.RI "\fBBLE\fP =(0x2)"
.br
.ti -1c
.RI "\fBNFC\fP =(0x4)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBTInterface\fP (int \fBtInterfaceCode\fP)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "final int \fBtInterfaceCode\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file TInterface\&.java\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "com\&.ethernom\&.android\&.etherapi\&.linkLayer\&.TInterface\&.TInterface (int tInterfaceCode)\fC [private]\fP"

.PP
Definition at line 10 of file TInterface\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "com\&.ethernom\&.android\&.etherapi\&.linkLayer\&.TInterface\&.BLE =(0x2)"

.PP
Definition at line 5 of file TInterface\&.java\&.
.SS "com\&.ethernom\&.android\&.etherapi\&.linkLayer\&.TInterface\&.NFC =(0x4)"

.PP
Definition at line 6 of file TInterface\&.java\&.
.SS "final int com\&.ethernom\&.android\&.etherapi\&.linkLayer\&.TInterface\&.tInterfaceCode\fC [private]\fP"

.PP
Definition at line 8 of file TInterface\&.java\&.
.SS "com\&.ethernom\&.android\&.etherapi\&.linkLayer\&.TInterface\&.USB =(0x1)"

.PP
Definition at line 4 of file TInterface\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for EtherAPI from the source code\&.
