.TH "com.ethernom.android.etherapi.EtherAPIPackage" 3 "Fri Nov 1 2019" "EtherAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.ethernom.android.etherapi.EtherAPIPackage
.SH SYNOPSIS
.br
.PP
.PP
Inherits ReactPackage\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "List< Class<? extends JavaScriptModule > > \fBcreateJSModules\fP ()"
.br
.ti -1c
.RI "List< ViewManager > \fBcreateViewManagers\fP (ReactApplicationContext reactContext)"
.br
.ti -1c
.RI "List< NativeModule > \fBcreateNativeModules\fP (ReactApplicationContext reactContext)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 12 of file EtherAPIPackage\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "List<Class<? extends JavaScriptModule> > com\&.ethernom\&.android\&.etherapi\&.EtherAPIPackage\&.createJSModules ()"

.PP
Definition at line 13 of file EtherAPIPackage\&.java\&.
.SS "List<NativeModule> com\&.ethernom\&.android\&.etherapi\&.EtherAPIPackage\&.createNativeModules (ReactApplicationContext reactContext)"

.PP
Definition at line 23 of file EtherAPIPackage\&.java\&.
.SS "List<ViewManager> com\&.ethernom\&.android\&.etherapi\&.EtherAPIPackage\&.createViewManagers (ReactApplicationContext reactContext)"

.PP
Definition at line 18 of file EtherAPIPackage\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for EtherAPI from the source code\&.
