.TH "com.ethernom.android.etherapi.UnSolicitedEventListener" 3 "Fri Nov 1 2019" "EtherAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.ethernom.android.etherapi.UnSolicitedEventListener
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBonUnsolicitedEvent\fP (int resultCode, byte[] payload)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 3 of file UnSolicitedEventListener\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void com\&.ethernom\&.android\&.etherapi\&.UnSolicitedEventListener\&.onUnsolicitedEvent (int resultCode, byte [] payload)"


.SH "Author"
.PP 
Generated automatically by Doxygen for EtherAPI from the source code\&.
