.TH "com.ethernom.android.etherapi.linkLayer.EtherBTAdapter" 3 "Fri Nov 1 2019" "EtherAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
com.ethernom.android.etherapi.linkLayer.EtherBTAdapter
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBcom\&.ethernom\&.android\&.etherapi\&.linkLayer\&.EtherCommAdapter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTInterface\fP \fBGetInterface\fP ()"
.br
.ti -1c
.RI "String \fBGetAdapterAddress\fP ()"
.br
.ti -1c
.RI "void \fBSetAdapterAddress\fP (String adapterAddress)"
.br
.ti -1c
.RI "void \fBStopDiscovery\fP ()"
.br
.ti -1c
.RI "void \fBCardClose\fP ()"
.br
.ti -1c
.RI "UUID \fBconvertFromInteger\fP (int i)"
.br
.ti -1c
.RI "void \fBCardOpen\fP (\fBCardInfo\fP cardInfo)"
.br
.ti -1c
.RI "void \fBInit\fP (int servicePort, long secsTimeout, boolean allowDuplicates, boolean stopScanOnWrite, Context context)"
.br
.ti -1c
.RI "void \fBDiscover\fP ()"
.br
.ti -1c
.RI "void \fBWriteToCard\fP (byte[] transportPacket)"
.br
.in -1c
.SS "Package Attributes"

.in +1c
.ti -1c
.RI "BluetoothGattCallback \fBgattCallback\fP"
.br
.in -1c
.SS "Static Package Attributes"

.in +1c
.ti -1c
.RI "static String \fBTAG\fP = 'EtherBTAdapter'"
.br
.ti -1c
.RI "static UUID \fBETH_serviceUUID\fP = UUID\&.fromString('19490001\-5537\-4F5E\-99CA\-290F4FBFF142')"
.br
.ti -1c
.RI "static UUID \fBETH_characteristicUUID\fP = UUID\&.fromString('19490002\-5537\-4F5E\-99CA\-290F4FBFF142')"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "void \fBscanLeDevice\fP (final boolean enable)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "String \fB_adapterAddress\fP"
.br
.ti -1c
.RI "Context \fB_context\fP"
.br
.ti -1c
.RI "\fBCardInfo\fP \fB_cardInfo\fP"
.br
.ti -1c
.RI "int \fB_servicePort\fP"
.br
.ti -1c
.RI "BluetoothAdapter \fBmBluetoothAdapter\fP"
.br
.ti -1c
.RI "Handler \fBmHandler\fP"
.br
.ti -1c
.RI "long \fB_scanMSecsTimeout\fP = 30000"
.br
.ti -1c
.RI "BluetoothLeScanner \fBmLEScanner\fP"
.br
.ti -1c
.RI "ScanSettings \fBsettings\fP"
.br
.ti -1c
.RI "List< ScanFilter > \fBfilters\fP"
.br
.ti -1c
.RI "BluetoothDevice \fBperiphEthCard\fP"
.br
.ti -1c
.RI "BluetoothGatt \fBgatt\fP"
.br
.ti -1c
.RI "BluetoothGattCharacteristic \fBethCharacteristic\fP"
.br
.ti -1c
.RI "String \fBeth_advServiceUUD\fP"
.br
.ti -1c
.RI "ScanCallback \fBmScanCallback\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Definition at line 33 of file EtherBTAdapter\&.java\&.
.SH "Member Function Documentation"
.PP 
.SS "void com\&.ethernom\&.android\&.etherapi\&.linkLayer\&.EtherBTAdapter\&.CardClose ()"

.PP
Definition at line 97 of file EtherBTAdapter\&.java\&.
.SS "void com\&.ethernom\&.android\&.etherapi\&.linkLayer\&.EtherBTAdapter\&.CardOpen (\fBCardInfo\fP cardInfo)"

.PP
Definition at line 112 of file EtherBTAdapter\&.java\&.
.SS "UUID com\&.ethernom\&.android\&.etherapi\&.linkLayer\&.EtherBTAdapter\&.convertFromInteger (int i)"

.PP
Definition at line 104 of file EtherBTAdapter\&.java\&.
.SS "void com\&.ethernom\&.android\&.etherapi\&.linkLayer\&.EtherBTAdapter\&.Discover ()"

.PP
Definition at line 219 of file EtherBTAdapter\&.java\&.
.SS "String com\&.ethernom\&.android\&.etherapi\&.linkLayer\&.EtherBTAdapter\&.GetAdapterAddress ()"

.PP
Definition at line 64 of file EtherBTAdapter\&.java\&.
.SS "\fBTInterface\fP com\&.ethernom\&.android\&.etherapi\&.linkLayer\&.EtherBTAdapter\&.GetInterface ()"

.PP
Definition at line 57 of file EtherBTAdapter\&.java\&.
.SS "void com\&.ethernom\&.android\&.etherapi\&.linkLayer\&.EtherBTAdapter\&.Init (int servicePort, long secsTimeout, boolean allowDuplicates, boolean stopScanOnWrite, Context context)"

.PP
Definition at line 201 of file EtherBTAdapter\&.java\&.
.SS "void com\&.ethernom\&.android\&.etherapi\&.linkLayer\&.EtherBTAdapter\&.scanLeDevice (final boolean enable)\fC [private]\fP"

.PP
Definition at line 76 of file EtherBTAdapter\&.java\&.
.SS "void com\&.ethernom\&.android\&.etherapi\&.linkLayer\&.EtherBTAdapter\&.SetAdapterAddress (String adapterAddress)"

.PP
Definition at line 69 of file EtherBTAdapter\&.java\&.
.SS "void com\&.ethernom\&.android\&.etherapi\&.linkLayer\&.EtherBTAdapter\&.StopDiscovery ()"

.PP
Definition at line 73 of file EtherBTAdapter\&.java\&.
.SS "void com\&.ethernom\&.android\&.etherapi\&.linkLayer\&.EtherBTAdapter\&.WriteToCard (byte [] transportPacket)"

.PP
Definition at line 240 of file EtherBTAdapter\&.java\&.
.SH "Member Data Documentation"
.PP 
.SS "String com\&.ethernom\&.android\&.etherapi\&.linkLayer\&.EtherBTAdapter\&._adapterAddress\fC [private]\fP"

.PP
Definition at line 39 of file EtherBTAdapter\&.java\&.
.SS "\fBCardInfo\fP com\&.ethernom\&.android\&.etherapi\&.linkLayer\&.EtherBTAdapter\&._cardInfo\fC [private]\fP"

.PP
Definition at line 41 of file EtherBTAdapter\&.java\&.
.SS "Context com\&.ethernom\&.android\&.etherapi\&.linkLayer\&.EtherBTAdapter\&._context\fC [private]\fP"

.PP
Definition at line 40 of file EtherBTAdapter\&.java\&.
.SS "long com\&.ethernom\&.android\&.etherapi\&.linkLayer\&.EtherBTAdapter\&._scanMSecsTimeout = 30000\fC [private]\fP"

.PP
Definition at line 46 of file EtherBTAdapter\&.java\&.
.SS "int com\&.ethernom\&.android\&.etherapi\&.linkLayer\&.EtherBTAdapter\&._servicePort\fC [private]\fP"

.PP
Definition at line 42 of file EtherBTAdapter\&.java\&.
.SS "String com\&.ethernom\&.android\&.etherapi\&.linkLayer\&.EtherBTAdapter\&.eth_advServiceUUD\fC [private]\fP"

.PP
Definition at line 54 of file EtherBTAdapter\&.java\&.
.SS "UUID com\&.ethernom\&.android\&.etherapi\&.linkLayer\&.EtherBTAdapter\&.ETH_characteristicUUID = UUID\&.fromString('19490002\-5537\-4F5E\-99CA\-290F4FBFF142')\fC [static]\fP, \fC [package]\fP"

.PP
Definition at line 37 of file EtherBTAdapter\&.java\&.
.SS "UUID com\&.ethernom\&.android\&.etherapi\&.linkLayer\&.EtherBTAdapter\&.ETH_serviceUUID = UUID\&.fromString('19490001\-5537\-4F5E\-99CA\-290F4FBFF142')\fC [static]\fP, \fC [package]\fP"

.PP
Definition at line 36 of file EtherBTAdapter\&.java\&.
.SS "BluetoothGattCharacteristic com\&.ethernom\&.android\&.etherapi\&.linkLayer\&.EtherBTAdapter\&.ethCharacteristic\fC [private]\fP"

.PP
Definition at line 52 of file EtherBTAdapter\&.java\&.
.SS "List<ScanFilter> com\&.ethernom\&.android\&.etherapi\&.linkLayer\&.EtherBTAdapter\&.filters\fC [private]\fP"

.PP
Definition at line 49 of file EtherBTAdapter\&.java\&.
.SS "BluetoothGatt com\&.ethernom\&.android\&.etherapi\&.linkLayer\&.EtherBTAdapter\&.gatt\fC [private]\fP"

.PP
Definition at line 51 of file EtherBTAdapter\&.java\&.
.SS "BluetoothGattCallback com\&.ethernom\&.android\&.etherapi\&.linkLayer\&.EtherBTAdapter\&.gattCallback\fC [package]\fP"

.PP
Definition at line 121 of file EtherBTAdapter\&.java\&.
.SS "BluetoothAdapter com\&.ethernom\&.android\&.etherapi\&.linkLayer\&.EtherBTAdapter\&.mBluetoothAdapter\fC [private]\fP"

.PP
Definition at line 44 of file EtherBTAdapter\&.java\&.
.SS "Handler com\&.ethernom\&.android\&.etherapi\&.linkLayer\&.EtherBTAdapter\&.mHandler\fC [private]\fP"

.PP
Definition at line 45 of file EtherBTAdapter\&.java\&.
.SS "BluetoothLeScanner com\&.ethernom\&.android\&.etherapi\&.linkLayer\&.EtherBTAdapter\&.mLEScanner\fC [private]\fP"

.PP
Definition at line 47 of file EtherBTAdapter\&.java\&.
.SS "ScanCallback com\&.ethernom\&.android\&.etherapi\&.linkLayer\&.EtherBTAdapter\&.mScanCallback\fC [private]\fP"

.PP
Definition at line 247 of file EtherBTAdapter\&.java\&.
.SS "BluetoothDevice com\&.ethernom\&.android\&.etherapi\&.linkLayer\&.EtherBTAdapter\&.periphEthCard\fC [private]\fP"

.PP
Definition at line 50 of file EtherBTAdapter\&.java\&.
.SS "ScanSettings com\&.ethernom\&.android\&.etherapi\&.linkLayer\&.EtherBTAdapter\&.settings\fC [private]\fP"

.PP
Definition at line 48 of file EtherBTAdapter\&.java\&.
.SS "String com\&.ethernom\&.android\&.etherapi\&.linkLayer\&.EtherBTAdapter\&.TAG = 'EtherBTAdapter'\fC [static]\fP, \fC [package]\fP"

.PP
Definition at line 34 of file EtherBTAdapter\&.java\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for EtherAPI from the source code\&.
