.TH "C:/Lyn/tmp/ethernom-api-master_10-31-19/android/src/main/java/com/ethernom/android/etherapi/ServiceEventListener.java" 3 "Fri Nov 1 2019" "EtherAPI" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Lyn/tmp/ethernom-api-master_10-31-19/android/src/main/java/com/ethernom/android/etherapi/ServiceEventListener.java
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcom\&.ethernom\&.android\&.etherapi\&.ServiceEventListener\fP"
.br
.in -1c
.SS "Packages"

.in +1c
.ti -1c
.RI "package \fBcom\&.ethernom\&.android\&.etherapi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for EtherAPI from the source code\&.
